spring:
  config:
    import: optional:file:.docker/test/.env[.properties]

  jpa:
    show-sql: true
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show-sql: true
        SQL: trace
        format_sql: true
        use_sql_comments: true
        type:
          descriptor:
            sql: trace

  h2:
    console:
      enabled: false

  datasource:
    hikari:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:mem:testdb
      username: sa
      password:

  data:
    redis:
      host: ${INFRA_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

logging:
  level:
    root: info


freshr:
  minio:
    bucket: ${MINIO_BUCKET_NAME}
    access: ${MINIO_USERNAME}
    secret: ${MINIO_PASSWORD}
    host: ${INFRA_PROTOCOL}://${INFRA_HOST}:${MINIO_API_PORT}
    default-minute: 1
